# Generated by Django 4.2.10 on 2024-02-20 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_attrcategory_remove_attribute_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrType',
            fields=[
                ('datatype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.datatype')),
                ('value', models.CharField(max_length=100)),
            ],
            bases=('attributes.datatype',),
        ),
        migrations.RenameModel(
            old_name='Bool',
            new_name='BoolType',
        ),
        migrations.RenameModel(
            old_name='Float',
            new_name='FloatType',
        ),
        migrations.RenameModel(
            old_name='Int',
            new_name='IntType',
        ),
        migrations.RemoveField(
            model_name='str',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='str',
            name='datatype_ptr',
        ),
        migrations.DeleteModel(
            name='AttrChoice',
        ),
        migrations.DeleteModel(
            name='Str',
        ),
        migrations.AddConstraint(
            model_name='strtype',
            constraint=models.UniqueConstraint(fields=('value',), name='unique_value'),
        ),
    ]
