# Generated by Django 4.2.10 on 2024-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_strtypechoice_alter_strtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strtype',
            name='value',
            field=models.ManyToManyField(blank=True, null=True, to='attributes.strtypechoice'),
        ),
    ]
