# Generated by Django 4.2.10 on 2024-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0006_alter_strtype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strtype',
            name='value',
            field=models.ManyToManyField(blank=True, related_name='str_types', to='attributes.strtypechoice'),
        ),
    ]
