# Generated by Django 4.2.10 on 2024-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_alter_strtype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
