# Generated by Django 4.2.10 on 2024-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0008_alter_datatype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name_many',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='название множественного числа ЕИ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=5, unique=True, verbose_name='символ ЕИ'),
        ),
    ]
