# Generated by Django 4.2.10 on 2024-02-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('attributes', '0009_unit_name_many_alter_unit_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='contenttypes.contenttype'),
        ),
    ]
