# Generated by Django 4.2.10 on 2024-02-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('attributes', '0010_alter_attribute_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
