# Generated by Django 4.2.10 on 2024-02-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0005_remove_address_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0002_warehouse_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='название магазина')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='addresses.address', verbose_name='адрес')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to=settings.AUTH_USER_MODEL)),
                ('warehouses', models.ManyToManyField(related_name='outlets', to='warehouses.warehouse', verbose_name='Склады')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.AddConstraint(
            model_name='outlet',
            constraint=models.UniqueConstraint(fields=('title', 'address'), name='\noutlets_outlet_title_address_unique'),
        ),
    ]
