# Generated by Django 4.2.10 on 2024-02-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_name_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='title',
        ),
    ]
