# Generated by Django 4.2.10 on 2024-02-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Область'),
            preserve_default=False,
        ),
    ]
