# Generated by Django 4.2.10 on 2024-02-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_region_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'регион', 'verbose_name_plural': 'регионы'},
        ),
        migrations.AddField(
            model_name='address',
            name='liter',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='литер'),
        ),
    ]
