# Generated by Django 4.2.10 on 2024-02-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-rating',), 'verbose_name': 'рейтинг', 'verbose_name_plural': 'рейтинги'},
        ),
    ]
