# Generated by Django 4.2.10 on 2024-02-19 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='название склада')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='addresses.address', verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('title', 'address'), name='\nwarehouses_warehouse_title_address_unique'),
        ),
    ]
